interface PDFQuestion {
  number: number;
  question: string;
  answer: string;
  difficulty: string;
  category: string;
}

interface PDFOptions {
  title: string;
  role: string;
  level: string;
  difficulty: string;
  type: string;
  date: string;
  questions: PDFQuestion[];
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function diffColor(d: string): string {
  if (d === "Easy") return "#16a34a";
  if (d === "Hard") return "#dc2626";
  return "#d97706";
}

export function generatePDF(opts: PDFOptions): void {
  const questionsHtml = opts.questions
    .map(
      (q) => `
    <div class="question-block">
      <div class="question-header">
        <span class="q-number">${q.number}</span>
        <span class="badge" style="background:${diffColor(q.difficulty)}20;color:${diffColor(q.difficulty)}">${escapeHtml(q.difficulty)}</span>
        <span class="badge category">${escapeHtml(q.category)}</span>
      </div>
      <p class="question-text"><strong>Q:</strong> ${escapeHtml(q.question)}</p>
      <div class="answer-block">
        <p class="answer-label">Model Answer</p>
        <p class="answer-text">${escapeHtml(q.answer)}</p>
      </div>
    </div>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>${escapeHtml(opts.title)}</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:32px;color:#1f2328;font-size:13px;line-height:1.6}
  h1{font-size:22px;font-weight:700;margin:0 0 4px}
  .meta{color:#57606a;font-size:12px;margin-bottom:24px}
  .meta span{margin-right:16px}
  .question-block{border:1px solid #e5e7eb;border-radius:10px;padding:16px;margin-bottom:16px;page-break-inside:avoid}
  .question-header{display:flex;align-items:center;gap:8px;margin-bottom:10px}
  .q-number{width:24px;height:24px;border-radius:50%;background:#dbeafe;color:#1d4ed8;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0}
  .badge{font-size:11px;font-weight:600;padding:2px 8px;border-radius:20px}
  .category{background:#f1f5f9;color:#475569}
  .question-text{margin:0 0 12px;font-weight:500;color:#1f2328}
  .answer-block{background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:12px}
  .answer-label{font-size:10px;font-weight:700;color:#1d4ed8;text-transform:uppercase;letter-spacing:.05em;margin:0 0 6px}
  .answer-text{margin:0;color:#374151}
  .footer{text-align:center;font-size:11px;color:#9ca3af;margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb}
  @media print{body{padding:20px}.question-block{page-break-inside:avoid}}
</style>
</head>
<body>
  <h1>${escapeHtml(opts.title)}</h1>
  <div class="meta">
    <span>Role: <strong>${escapeHtml(opts.role)}</strong></span>
    <span>Level: <strong>${escapeHtml(opts.level)}</strong></span>
    <span>Difficulty: <strong>${escapeHtml(opts.difficulty)}</strong></span>
    <span>Type: <strong>${escapeHtml(opts.type)}</strong></span>
    <span>Questions: <strong>${opts.questions.length}</strong></span>
    <span>Date: <strong>${escapeHtml(opts.date)}</strong></span>
  </div>
  ${questionsHtml}
  <div class="footer">Generated by InterviewAI · ${escapeHtml(opts.date)}</div>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 500);
}
